### ISSUE TITLE
Issues at creating PR

### ISSUE THREAD

**Issue by rhcpfan** [ChristianFox/KFXLog#1]
Hello and thanks for the awesome work you've done, the code is written sooo nice!

I've integrated the logger in one of my projects and I needed a way to delete some of the log files from the KFXLogFilesMasterTVC, so I have implemented a swipe-to-delete functionality 😄 

I wanted to make a pull request hoping that others would find it useful, but I am having some issues at publishing the feature branch... 

The error is: 

> ERROR: Permission to ChristianFox/KFXLog.git denied to rhcpfan.
fatal: Could not read from remote repository.
>
> Please make sure you have the correct access rights
and the repository exists.

Can anyone contribute to the awesome work you've been doing?

Best regards and thanks again for saving me a lot of time and from a lot of trouble 👍

**Comment by ChristianFox** [comment]
Hi, thanks for the nice feedback :) . I've only just seen this so a huge apology for not having replied before now.
I'm not sure what would be causing that, I haven't deliberately blocked (or allowed) any collaboration.
I did add a purge log files method in v1.20 which also solves the same problem.

Are you still using KFXLog? Do you still want to do a PR?
